name: Build Flutter App

on:
  workflow_dispatch:
    inputs:
      platform:
        description: '选择要构建的平台'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - android
          - ios
          - web
          - windows
          - macos
          - linux

jobs:
  build-android:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && (github.event.inputs.platform == 'all' || github.event.inputs.platform == 'android') || github.event_name != 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.36.0-0.4.pre'
          channel: 'beta'
      
      - name: Get dependencies
        run: flutter pub get
      
      - name: Build APK
        run: flutter build apk --release
      
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-release
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 30

  build-ios:
    runs-on: macos-latest
    if: github.event_name == 'workflow_dispatch' && (github.event.inputs.platform == 'all' || github.event.inputs.platform == 'ios') || github.event_name != 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.36.0-0.4.pre'
          channel: 'beta'
      
      - name: Get dependencies
        run: flutter pub get
      
      - name: Build iOS
        run: flutter build ios --release --no-codesign
      
      - name: Upload iOS build
        uses: actions/upload-artifact@v4
        with:
          name: ios-release
          path: build/ios/iphoneos
          retention-days: 30

  build-web:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && (github.event.inputs.platform == 'all' || github.event.inputs.platform == 'web') || github.event_name != 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.36.0-0.4.pre'
          channel: 'beta'
      
      - name: Get dependencies
        run: flutter pub get
      
      - name: Build Web
        run: flutter build web --release
      
      - name: Upload Web build
        uses: actions/upload-artifact@v4
        with:
          name: web-release
          path: build/web
          retention-days: 30

  build-windows:
    runs-on: windows-latest
    if: github.event_name == 'workflow_dispatch' && (github.event.inputs.platform == 'all' || github.event.inputs.platform == 'windows') || github.event_name != 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.36.0-0.4.pre'
          channel: 'beta'
      
      - name: Get dependencies
        run: flutter pub get
      
      - name: Enable Windows desktop
        run: flutter config --enable-windows-desktop
      
      - name: Check Flutter doctor
        run: flutter doctor -v
      
      - name: Build Windows
        run: flutter build windows --release
      
      - name: List build directory
        run: |
          echo "Checking build directory structure..."
          dir build
          dir build\windows
          dir build\windows\x64
          dir build\windows\x64\runner
          dir build\windows\x64\runner\Release
      
      - name: Upload Windows build
        uses: actions/upload-artifact@v4
        with:
          name: windows-release
          path: build/windows/x64/runner/Release
          retention-days: 30

  build-macos:
    runs-on: macos-latest
    if: github.event_name == 'workflow_dispatch' && (github.event.inputs.platform == 'all' || github.event.inputs.platform == 'macos') || github.event_name != 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.36.0-0.4.pre'
          channel: 'beta'
      
      - name: Get dependencies
        run: flutter pub get
      
      - name: Build macOS
        run: flutter build macos --release
      
      - name: Upload macOS build
        uses: actions/upload-artifact@v4
        with:
          name: macos-release
          path: build/macos/Build/Products/Release
          retention-days: 30

  build-linux:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && (github.event.inputs.platform == 'all' || github.event.inputs.platform == 'linux') || github.event_name != 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev libsecret-1-dev libblkid-dev liblzma-dev libsqlite3-dev
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.36.0-0.4.pre'
          channel: 'beta'
      
      - name: Get dependencies
        run: flutter pub get
      
      - name: Enable Linux desktop
        run: flutter config --enable-linux-desktop
      
      - name: Check Flutter doctor
        run: flutter doctor -v
      
      - name: Build Linux
        run: flutter build linux --release
      
      - name: Upload Linux build
        uses: actions/upload-artifact@v4
        with:
          name: linux-release
          path: build/linux/x64/release/bundle
          retention-days: 30
